name: Build Test

on:
  push:
    branches:
      - main

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - name: Git Checkout
        uses: actions/checkout@v4
      - name: pnpm Setup
        uses: pnpm/action-setup@v3
        with:
          version: '9.1.2'
      - name: Install node modules
        run: pnpm install
      - name: Build Test
        run: pnpm run build
